Implement PairSemigroup
vmware/database-stream-processor pull request #264
Opened 2023-01-12 19:43 UTC by mbudiu-vmw

Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
This is needed for average, for example

2023-01-12 20:57 UTC, mbudiu-vmw commented
How can coverage decrease when I implement one function and add tests for it *and* 1 more?

2023-01-13 16:51 UTC, ryzhyk requested changes

2023-01-13 16:51 UTC, ryzhyk commented on src/algebra/mod.rs
> +    R: SemigroupValue,
These two bounds are redundant.

2023-01-13 20:07 UTC, ryzhyk approved these changes

2023-01-14 00:01 UTC, mbudiu-vmw commented
Do we run in CI randon python scripts we pull from the internet? This sounds dangerous to me.
The bench-skylake-2x failed with this error:
```
 python3 gh-pages/_scripts/compare_nexmark.py
  File "/home/github-runner/actions-runner/_work/database-stream-processor/database-stream-processor/gh-pages/_scripts/compare_nexmark.py", line 158
    df_compare['Peak RSS diff'] = current_results['allocstats_after_peak_rss'] -
                                                                                ^
SyntaxError: invalid syntax
```
Because of this failure I cannot merge this PR.

2023-01-14 00:12 UTC, ryzhyk commented
This is @gz's script.  I think he made a typo while fixing something else earlier today.  This PR can be merged, the bug is unrelated.

2023-01-14 00:34 UTC, mbudiu-vmw commented
I could not find the script in the repository.
My merge button is disabled.

2023-01-14 00:41 UTC, mbudiu-vmw commented
Turns out I also need to derive Clone for it...

2023-01-14 00:41 UTC, closed without merging

2023-01-14 00:41 UTC, mbudiu-vmw commented
It is too complicated to fight with the CI of this repo, I will add this to the SQL runtime library