Camera-ready version
vmware/database-stream-processor pull request #336
Opened 2023-03-16 01:18 UTC by mbudiu-vmw

This mostly shrinks the document to fit in 12 pages.
We will need to do a final update once we get the ofificial DOI

2023-03-16 01:19 UTC, mbudiu-vmw commented
@ryzhyk you should probably build this to make sure it works, but a careful proofreading may not be necessary if you are busy.

2023-03-17 15:58 UTC, ryzhyk requested changes

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/intro2.tex
> +basic stream operator, is \emph{stream integration}, the inverse of
typo

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/intro2.tex
> +In this paper we omits proofs, they can be found in an extensive
omit

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/intro2.tex
> +machine-checked proofs of correctness for all the theorems in this
"of correctness" is redundant here

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/relational.tex
> +deploying a new plan requires in general to construct its internal
to construct -> constructing

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/streams.tex
> +$S(\zm_A(s)) = \zm_B(S(s))$ for all $s \in \stream{A}$; in other words, the
typo

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/streams.tex
> +The lifting a bilinear function $f$ is
of

2023-03-17 15:58 UTC, ryzhyk commented on doc/vldb23/streams.tex
> +Here we define of IVM and analyze its properties.
remove "of"

2023-03-17 16:44 UTC, mbudiu-vmw commented
I will wait for Tej to comment before I commit a new pdf

2023-03-24 18:09 UTC, mbudiu-vmw commented
@ryzhyk this is supposed to be the final-final version of the vldb paper, please let me know if I can merge it.

2023-03-27 20:35 UTC, ryzhyk approved these changes

2023-03-27 20:36 UTC, merged