Import and export streams from subcircuits cleanly.
vmware/database-stream-processor pull request #37
Opened 2022-02-11 19:21 UTC by ryzhyk

We eliminate the unsoundness introduced by the onwership-aware scheduling
model and implement a clean and general method to import streams from
a parent circuit to a subcircuit and export streams from the subcircuit
to the parent.

The unsoundness was caused by the `Stream::enter` API that imported a parent
stream to the child circuit.  The child circuit can read from the parent
stream multiple times per parent clock tick.  This was ok while the read
operation was idempotent; however the new `Stream::take` API is no
longer idempotent, destroying the contents of the stream after a
fixed number of calls.  Thus the imported stream could only be used safely
by a special operator like `NestedSource` that reads from the stream
once per parent clock tick.

Import
------

We introduce a new operator trait `ImportOperator` for operators that
make the contents of a parent stream visible to the child subcircuit.

An import operators spans two clock domains: it reads a single
value from the parent stream per parent clock tick and produces
a stream of outputs in the nested circuit, one for each nested
clock tick.

We so far implement one instance of `ImportOperator` -- the delta_0
operator, which outputs the value from the parent stream in the first
clock cycle, followed by zeros.  But other useful implementations
are possible, e.g., an operator that outputs the parent value repeatedly
on each nested clock tick.

As a result, the circuit architecture has been simplified slightly,
since all edges now have their source node in the local circuit
(`Edge::from` no longer needs to be an `Option`).

We remove the unsafe `Stream::enter` API and the no-longer-necessary
NestedSource operator.

Export
------

The export story is not quite symmetric.  We could define an
operator that accumulates inputs throughout the execution of the nested
circuit and writes a single value to the parent stream after the nested
clock epoch ends.  But in reality this state is often (typically?)
available elsewhere in the circuit and should not be duplicated.  The
output of a nested circuit is usually the value accumulated in some sort
of an integrator, in z^-1 operator.  z^-1 is a strict operator meaning
that it always stores a value ready to output in the next clock cycle,
so all we need to do is to use that value when the clock epoch ends.

So we add a new method `add_feedback_with_export` that returns two
streams: a local feedback stream and a stream in the parent scope that
will receive the final value stored in the operator after the last
nested clock tick.

Probes
------

Probes provide a way to define a condition to terminate iteration based
on the contents of one or more stream.  E.g., the DBSP integral operator
terminates the circuit when its input is equal to zero.  Internally, a
probe is just an `Inspect` operator that evaluates a condition, e.g.,
`is_zero`, and stores its value in a Boolean flag.  Use `stream.probe()`
to create a new probe bound to a stream, and `circuit.iterate_with_probe()`
to create a nested circuit that iterates until the probe condition is
satisfied.  Finally, `circuit.iterate_with_probes()` will iterate until
multiple probes are satisfied simultaneously.

2022-02-12 00:20 UTC, mbudiu-vmw requested changes

2022-02-12 00:20 UTC, mbudiu-vmw commented on src/circuit/circuit_builder.rs
> +    unsafe fn clock_end(&mut self, scope: Scope) {
this also seems to have two halves

2022-02-12 00:40 UTC, ryzhyk commented on src/circuit/circuit_builder.rs
> +            (output_node, (output_stream, export_stream, connector))
Clippy agrees with you. I'll try to simplify this.

2022-02-12 00:40 UTC, ryzhyk commented on src/operator/probe.rs
> +    pub fn probe<F>(&self, probe_func: F) -> Probe<Circuit<P>>
Conditional is good

2022-02-12 00:41 UTC, ryzhyk commented on src/operator/probe.rs
> +                let reachable_circuit = |init: Stream<Circuit<Circuit<()>>, ZSetHashMap<usize, isize>>| {
There are different types of zsets, so we'd still need to write the type explicitly.

2022-02-12 00:42 UTC, mbudiu-vmw commented on src/circuit/operator_traits.rs
> +    /// clock_start(1) // Start outer clock.
The scope is equivalent to the nesting level of nested timestamps of DD.
What happens if you call with the wrong argument (0 instead of 1)?

2022-02-12 00:42 UTC, ryzhyk commented on src/operator/probe.rs
> +                    let successor_set = |nodes: &ZSetHashMap<usize, isize>, edges: &ZSetHashMap<(usize, usize), isize>| {
There will be a proper join operator doing just that.  This is just for testing.

2022-02-12 04:47 UTC, ryzhyk commented on src/circuit/operator_traits.rs
> +    /// clock_start(1) // Start outer clock.
Only the framework can call these functions, so unless the framework is buggy this shouldn't happen.

2022-02-12 04:49 UTC, ryzhyk commented on src/operator/probe.rs
> +                let reachable_circuit = |init: Stream<Circuit<Circuit<()>>, ZSetHashMap<usize, isize>>| {
There will be different types of zsets potentially, e.g., LSM tree or Btree-based z-set.

2022-02-14 18:50 UTC, Kixiron reviewed
Have you considered addressing scoping/imports/exports/children in the same way that timely does with lifetimes? I think that's a very natural way to express this since it inherently makes a hierarchy of scopes

2022-02-14 18:50 UTC, Kixiron commented on src/circuit/circuit_builder.rs
> +    }
Shouldn't `Circuit` implement `PartialEq` and this just be an eq check?

2022-02-14 18:50 UTC, Kixiron commented on src/circuit/circuit_builder.rs
> +    }
This should be a `PartialEq` implementation

2022-02-14 18:50 UTC, Kixiron commented on src/circuit/circuit_builder.rs
> +        self.add_node(|id| {
```suggestion
        assert!(self.is_child_of(parent_stream.circuit()));

        self.add_node(|id| {
```

2022-02-14 18:50 UTC, Kixiron commented on src/circuit/circuit_builder.rs
> +        Self {
```suggestion
        assert!(Circuit::ptr_eq(&circuit.parent(), parent_stream.circuit()));

        Self {
```

2022-02-14 18:50 UTC, Kixiron commented on src/operator/condition.rs
> +use crate::circuit::{
```suggestion
use std::{cell::RefCell, marker::PhantomData, rc::Rc};
use crate::circuit::{
```

2022-02-14 19:53 UTC, merged